### ISSUE TITLE
Work with templates

### ISSUE THREAD

**Issue by pwFoo** [blikblum/tinybind#11]
> Remove component feature -> incomplete, untested code. Use web components libraries like SkateJs or LitElement

So to fill templates with data the template code have to be present in the dom already or inserted by custom code / a component lib like SkateJS or LitElement?

That's fine for me, but I search a way to keep files separated. So could you recommend a (small, easy) lib? I haven't used web components before so I just read about rivets or vuejs components so far. But I like to keep it small. That's why I would prefer tinybind ;)

**Comment by blikblum** [comment]
Working with custom elements does not require a new framework library

See this simple element i just created: https://codepen.io/blikblum/pen/zywdPB

In v2 i will be adding such element out of the box
