### ISSUE TITLE
Reduce size based on wrist lib?

### ISSUE THREAD

**Issue by pwFoo** [blikblum/tinybind#13]
I searched data binding solutions / libs before I found  tinybind (rivets) and also found the small lib wrist (4,59KB, 1,43KB minified).

> Minimalistic utility for generic one/two ways data bindings. https://medium.com/@WebReflection/js-dom-data-bindings-in-2017-1545f38cfdc8#.yy4lk656m

> An easy way to bind or react to properties change.
> It also works with input elements and their value, checked, or disabled too.

https://github.com/WebReflection/wrist

Maybe a way to reduce the size of tinybind by rewrite it based on wrist?

**Comment by blikblum** [comment]
> Maybe a way to reduce the size of tinybind by rewrite it based on wrist?

Internally tinybind does the same. Adding the tinybind features on top of wrist would increase code instead instead

**Comment by pwFoo** [comment]
Ok, thanks for feedback! 👍
