### ISSUE TITLE
Is tinybind still maintained?

### ISSUE THREAD

**Issue by pwFoo** [blikblum/tinybind#14]
At the moment there is no update with to code or issues. Is tinybind still maintained?
Maybe I should move to an active maintained project?

**Comment by blikblum** [comment]
>  Is tinybind still maintained?

Yes. Although there's not really much to be done.

I plan a 1.0 release with a few changes followed by a 2.0 release

**Comment by blikblum** [comment]
Just released v1 with web component feature and improved docs
