### ISSUE TITLE
Clearing array by .length= 0 not working

### ISSUE THREAD

**Issue by naranjamecanica** [blikblum/tinybind#2]
Hi I'm using your fork in a project (thanks!) and I found out that setting the length to 0 of an array kills bindings and does not update the view. 

See: https://jsfiddle.net/qx5091vd/2/

Is this something that can be implemented or is using one of the array methods the only way to go?

**Comment by blikblum** [comment]
Its a limitation. See vue docs https://vuejs.org/v2/guide/list.html#Caveats

Vue uses a similar techniq

**Comment by naranjamecanica** [comment]
Thanks for the info!
