### ISSUE TITLE
show and hide

### ISSUE THREAD

**Issue by julientype** [blikblum/tinybind#30]
visibility:hidden will keep the element in the page and occupies that space but does not show to the user. display:none will not be available in the page and does not occupy any space. The difference goes beyond style and is reflected in how the elements behave when manipulated with JavaScript

you have 2 action doing the same thing.....
show = should be   display  none
hide = should be visibility   hidden  

hide should let you keep binding where show stops all binding 

 el.style.visibility= value ? 'hidden ' : '';

like if i wanted to add elements to a hidden view array  not a problem  where show would not let you add....
hide.....   task list... if you want to run a record cursor....

**Comment by julientype** [comment]
i would add one for zindex where you can change the layer stack

**Comment by karneaud** [comment]
More information is needed here along with example code for reference
