### ISSUE TITLE
Question: How to get full keypath during routine function?

### ISSUE THREAD

**Issue by adelriosantiago** [blikblum/tinybind#35]
I came across the need to get the full keypath during the a routine call but I don't seem to know where to catch the full keypath for  `rv-each`, I only get the partial path, example:

For the data:

```js
items: [
    { todo: "get milk" },
    { todo: "buy meat" },
    { todo: "exercise" },
],
```

If I change the "get milk" and print the arguments of the binding in [this line](https://github.com/blikblum/tinybind/blob/master/dist/tinybind.js#L528), I get:

![image](https://user-images.githubusercontent.com/5462382/100804120-ec541380-33f1-11eb-820b-1b14b185a9b0.png)

As you can see it is only `item.todo` and not `items[0].todo` or `items[1].todo` or whatever the index is. **How can I get the full path?**

**Comment by karneaud** [comment]
I created a [demo](https://jsfiddle.net/23va1dsL/14/) with a use case for how `rv-each` is handled and this works as intended, but to access the full path would be along the lines of **items.0.todo, items.1.todo...etc.** however there is **no support** at the moment for dynamic **keypath** within the loop if this is what you're asking for.
