### ISSUE TITLE
is this library is dead as no issue seems to be replied from long time. Also there is no update from past two years ?

### ISSUE THREAD

**Issue by aubrijesh** [blikblum/tinybind#38]

**Comment by blikblum** [comment]
This library is basically done. It hit the limits of its design

**Comment by Pyetrek** [comment]
> This library is basically done. It hit the limits of its design

Possibly update the copyright in the readme to give an indication this project is still active?

**Comment by karneaud** [comment]
We're looking to revive it and keep it alive. Feel free to collaborate
