### ISSUE TITLE
Add built in animations

### ISSUE THREAD

**Issue by blikblum** [blikblum/tinybind#6]
For hide and show, like vue 1.x

**Comment by prionkor** [comment]
Thanks for the fork. Looks like rivetsjs is abandoned. I will check this out and migrate my rivetsjs project into tinybind when I get some time.

**Comment by pwFoo** [comment]
Found rivets as lightweight vuejs alternative and happy to see a maintained fork! 👍 

As "tiny" in tinybind you should keep file size in mind to keep it small I think.
Some features could be plugins if possible?

**Comment by karneaud** [comment]
Definitely like the suggestions here and would probably consider this idea as a plugin/ adapter/ component for future version. If any of you guys came up with anything feel free to fork with a test case for review via pull request
