### ISSUE TITLE
How to access index in rv-each?

### ISSUE THREAD

**Issue by trollkotze** [blikblum/tinybind#9]
The documentation says under "Differences from rivets.js":

> Change how scope of iteration binder works. Instead of copying properties down to children, uses a prototype like approach
> 
> Related: [486](https://github.com/mikeric/rivets/issues/486) [512](https://github.com/mikeric/rivets/issues/512) [417](https://github.com/mikeric/rivets/pull/417)
> Change how to customize index name in each binder (using an attribute)
> Related: [551](https://github.com/mikeric/rivets/issues/551) [552](https://github.com/mikeric/rivets/pull/552)

Issue [551](https://github.com/mikeric/rivets/issues/551) and pull-request [552](https://github.com/mikeric/rivets/pull/552) from rivets.js, which are referred to here, talk about this feature, but it's not clear how (and if) it is implemented in tinybind. The rivets.js generic `{ index }` does not work, nor the other syntax `{ %item% }` [that was later added in rivets](https://github.com/mikeric/rivets/commit/a46e3cfb94c471aa005816711f1619da4b3ab1c3).

Is it possible to access the iteration index inside rv-each in tinybind?

**Comment by trollkotze** [comment]
Oh, I found it. The syntax is `{$index}`.

Found it in the [example](https://github.com/blikblum/tinybind/blob/master/examples/dynamic-list.html).

But what about nested indexes? Rivets.js has this syntax now:
```
<ul rv-each-whatever="items">
  <li>{ %items% }: whatever</li>
</ul>
```
The index of the iterated array `items` here can be accessed with `{ %items% }`. In this way, it is possible to distinguish indexes of nested `rv-each` iterations.

Is something like that also possible in tinybind?

**Comment by trollkotze** [comment]
Oh, [I see](https://github.com/blikblum/tinybind/blob/master/src/binders.js#L72). That's how it works:
```
<ul rv-each-whatever="items" index-property="something">
  <li>{ something }: whatever</li>
</ul>
```

Would be worth documenting,  I think.

**Comment by blikblum** [comment]
Added docs in https://github.com/blikblum/tinybind/commit/a57e594ca5cab7831ddab79375a1d2506b995687

Should be online soon
